apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sfs-consul
spec:
  serviceName: svc-consul
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: "consul:1.0.6"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            #- name: GOSSIP_ENCRYPTION_KEY
            #  valueFrom:
            #    secretKeyRef:
            #      name: consul
            #      key: gossip-encryption-key
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bootstrap-expect=3" #expected server in cluster before electing one leader
            - "-retry-join=sfs-consul-0.svc-consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=sfs-consul-1.svc-consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=sfs-consul-2.svc-consul.$(NAMESPACE).svc.cluster.local"
            - "-client=0.0.0.0"
            #- "-config-file=/consul/config/server.json"
            - "-data-dir=/consul/data"
            - "-domain=cluster.local"
            #- "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"
            - "-server"
            - "-ui"
            - "-disable-host-node-id"
          volumeMounts:
            - name: data
              mountPath: /consul/data
          #  - name: config
          #    mountPath: /consul/config
          #  - name: tls
          #    mountPath: /etc/tls
          lifecycle:
            preStop:
              exec:
                command: ["consul", "leave"]
          ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: alt-port
            - containerPort: 53
              name: udp-port
            - containerPort: 8443
              name: https-port
            - containerPort: 8080
              name: http-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
      #volumes:
      #  - name: config
      #    configMap:
      #      name: consul
      #  - name: tls
      #    secret:
      #      secretName: consul  
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations: 
           volume.beta.kubernetes.io/storage-class: "standard"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-consul
  labels:
    name: consul-service
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: https
      port: 8443
      targetPort: 8443
    - name: rpc
      port: 8400
      targetPort: 8400
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: consuldns
      port: 8600
      targetPort: 8600
  selector:
    app: consul