apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfspvc
        lifecycle:
          postStart:
            exec:
              #Gives right to yorc user 
              command: ["chown", "1001:1001", "/exports"]
      volumes:
      - name: nfspvc
        persistentVolumeClaim:
          claimName: nfs-vol-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-vol-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
  #replace "default" by the name of the namespace you're deploying app
    server: svc-nfs-server.default.svc.cluster.local
    path: "/"

